-- drop table if exists recipes;

CREATE TABLE recipes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  ingredients TEXT NOT NULL,
  instructions TEXT NOT NULL,
  meal_type TEXT,
  image_url TEXT,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);