-- drop table if exists meals;
CREATE TABLE meals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day TEXT NOT NULL,
    recipe_id INTEGER
        REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);